FROM maven:3.8.6-amazoncorretto-17 as build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests
  
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/*.jar springdeskcurso.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "springdeskcurso.jar"]
