FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests
  
  # Etapa de runtime com Java 21
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar springdeskcurso.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "springdeskcurso.jar"]

